export enum lfpClassNames {
  Main = "lfp-main",
  Header = "lfp-header",
  HeaderText = "lfp-header__text",
  HeaderActions = "lfp-header__actions",
  Language = "lfp-language",
  LanguageInput = "lfp-language__input",
  LanguageInfo = "lfp-language__info",
  LanguageActions = "lfp-language__actions",
  FontList = "lfp-font-list",
  FontListHead = "lfp-font-list-head",
  FontListHeadText = "lfp-font-list-head__text",
  FontListHeadActions = "lfp-font-list-head__actions",
  FontListList = "lfp-font-list-list",
  FontDivider = "lfp-font-divider",
  FontRow = "lfp-font-row",
  FontRowSelected = "lfp-font-row-selected",
  FontRowText = "lfp-font-row__text",
  FontRowActions = "lfp-font-row__actions",
  Footer = "lfp-footer",
}
