export enum lfpClassNames {
  Main = "lfp-main",
  Header = "lfp-header",
  HeaderText = "lfp-header__text",
  HeaderActions = "lfp-header__actions",
  Language = "lfp-language",
  LanguageInput = "lfp-language__input",
  LanguageInfo = "lfp-language__info",
  LanguageActions = "lfp-language__actions",
  FontTable = "lfp-font-table",
  FontTableHead = "lfp-font-table-head",
  FontTableHeadText = "lfp-font-table-head__text",
  FontTableHeadActions = "lfp-font-table-head__actions",
  FontTableBody = "lfp-font-table-body",
  FontDivider = "lfp-font-divider",
  FontRow = "lfp-font-row",
  FontRowText = "lfp-font-row__text",
  FontRowActions = "lfp-font-row__actions",
  Footer = "lfp-footer",
}
