name: format-lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  format-lint:
    name: Checks formatting and linting on ${{ matrix.os }}, node ${{ matrix.node_version }}, pnpm ${{ matrix.pnpm_version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [20]
        pnpm_version: [8]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Check formatting
        run: pnpm format:check

      - name: Lint all projects
        run: pnpm lint --verbose
